experiment:
  name: Xgaze_resnet18
  root: ./exp/{name}
  data_dir: "/home/zhongrui/datasets/xgaze_224"
  batch_size: 50
  num_workers: 5
  dataset_type : xgaze

train:
  backbone: resnet18 #'resnet18''resnet34''resnet50''resnet101''resnet152''resnext50_32x4d' 'resnext101_32x8d''wide_resnet50_2''wide_resnet101_2':
  print_freq: 1000
  epochs: 25
  init_lr: 0.0001
  lr_patience: 10
  lr_decay_factor: 0.1
  save_freq: 5
  enable_val: true #这种情况默认使用train_test_split的val



test:
  dataset_type: 'xgaze'
  pretrained_expname: Xgaze
  test_dataset: "/home/zhongrui/datasets/xgaze_224" #含有test_train_split的数据集，用其中的test测试

  
  